### PR TITLE
Added WaitEvent, Monitor actions

### PR DESCRIPTION
**Pull request by diego-asterisk**
Just added the following actions:
WaitEvent
Monitor
StopMonitor
PauseMonitor
UnpauseMonitor
ChangeMonitor

### CODE REVIEW

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#33](https://github.com/emilianodellacasa/ruby-asterisk/issues/33) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) everybody who has role `REV` is banned at [#33](https://github.com/emilianodellacasa/ruby-asterisk/issues/33); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) everybody who has role `REV` is banned at [#33](https://github.com/emilianodellacasa/ruby-asterisk/issues/33); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by emilianodellacasa** [comment]
@diego-asterisk Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:emilianodellacasa/ruby-asterisk#33` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#33](https://github.com/emilianodellacasa/ruby-asterisk/issues/33) is now out of scope

**Pull request merged**
